### ISSUE TITLE
macros should be case-insensitive

### ISSUE THREAD

**Issue by globau** [JunSuzukiJapan/atom-keyboard-macros-vim#1]
in vim the macros are not case sensitive.  this allows you to quickly play the back because you don't have to release the shift key after typing @ 

in vim i frequently do:  qq (record) q, then @Q to replay.  this does not work in atom-keyboard-macros-vim, i have to do @q

**Comment by JunSuzukiJapan** [comment]
Oh, I didn't know.

I fixed this issue.
Try v0.1.3, please.

**Comment by helarqjsc** [comment]
I just tested it and can confirm that this issue is fixed now.

**Comment by JunSuzukiJapan** [comment]
@helarqjsc

Is this issue fixed?
I guess you talk about another issue (https://github.com/JunSuzukiJapan/atom-keyboard-macros-vim/issues/4).
Is my thinking correct?

**Comment by helarqjsc** [comment]
@JunSuzukiJapan No, I'm talking about this exact issue (#1). When I record a macro with `qq`, I can replay it with both `@q` and `@Q`, so the problem that @globau talked about is fixed.

The error from issue #4 is still present, I think.

**Comment by JunSuzukiJapan** [comment]
OK. I understand.
